<form action="" method="POST" enctype="multipart/form-data">
    <label for="title">Titre</label>
    <input type="text" name="title" placeholder="" id="title" value="<?= $title ?>">
    <label for="image">Image</label>
    <input type="file" id="image" name="image">
    <label for="description">Description</label>
    <textarea type="" name="description" id="description" placeholder=""><?= $description ?></textarea>
    <label for="price">Prix</label>
    <input type="tel" name="price" value="<?= $price ?>">
    <button class="button" type="submit">Modifier</button>
</form>

<footer></footer>