<h1>Ajouter un produit</h1>

<form action="" method="POST">
    <label for="title">Titre</label>
    <input type="text" name="title" id="title" value="<?= $title ?>">
    <?php if (isset($errors['title'])) : ?>
        <p class="alert alert-danger"><?= $errors['title']; ?></p>
    <?php endif; ?>
    <label for="image">Image</label>
    <input type="text" name="image" id="image" placeholder="Url..." value="<?= $image ?>">
    <?php if (isset($errors['image'])) : ?>
        <p class="alert alert-danger"><?= $errors['image']; ?></p>
    <?php endif; ?>
    <label for="description">Description</label>
    <textarea name="description" id="description" cols="30" rows="10" placeholder="Can i get some burger..."></textarea>
    <?php if (isset($errors['description'])) : ?>
        <p class="alert alert-danger"><?= $errors['description']; ?></p>
    <?php endif; ?>
    <label for="price">Prix</label>
    <input type="text" name="price" id="price" value="<?= $price ?>">
    <?php if (isset($errors['price'])) : ?>
        <p class="alert alert-danger"><?= $errors['price']; ?></p>
    <?php endif; ?>
    <button type="submit">Enregistrer</button>
</form>

<?php foreach ($foods as $food) : ?>
    <div class="card" style="width: 150px;">
        <img class="img-food" src="<?= asset('images/' . $food->getImage()) ?>" alt="">
        <h1 class="title-food"><?= $food->getTitle(); ?></h1>
        <p class="content-food"><?= $food->getDescription() ?></p>
        <div class="add-price">
            <h1 class="price-food"><?= $food->getPrice() ?> €</h1>
            <button class="button">Ajouter au panier</button>
        </div>
    </div>
<?php endforeach; ?>