<form action="" method="POST">
    <label for="title">Titre</label>
    <input type="text" name="title" placeholder="" id="title" value="<?= $title ?>">
    <label for="image">Image</label>
    <input type="text" name="image" id="image" value="<?= $image ?>">
    <label for="description">Description</label>
    <textarea type="" name="description" id="description" placeholder=""><?= $description ?></textarea>
    <label for="price">Prix</label>
    <input type="tel" name="price" value="<?= $price ?>">
    <button class="button" type="submit">Modifier</button>
</form>

<footer></footer>