<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $pageTitle ?></title>
    <?php if ($css) : ?>
        <link rel="stylesheet" href="<?= asset('css/' . $css) ?>">
    <?php endif; ?>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>

    <header>
        <nav class="navbar">
            <div class="nav-content">
                <div class="nav-logo">
                    <a href="<?= constructUrl('adminHome'); ?>">
                        <img src="<?= asset('images/nav-logo.png') ?>" alt="">
                    </a>
                </div>
                <div class="nav-links">
                    <?php if (!isConnected()) : ?>
                        <div></div>
                    <?php else : ?>
                        <a href="<?= constructUrl('logout'); ?>">Se déconnecter</a>
                    <?php endif; ?>
                </div>
            </div>

        </nav>
    </header>
    <main>
        <!-- Message flash -->
        <?php if (isset($flashMessage) && $flashMessage) : ?>
            <p class="alert alert-success"><?= $flashMessage ?></p>
        <?php endif; ?>

        <!-- Contenu de la page -->
        <?php include $template . '.phtml'; ?>
    </main>
</body>

</html>