<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $pageTitle ?></title>
    <?php if ($css) : ?>
        <link rel="stylesheet" href="<?= asset('css/' . $css) ?>">
    <?php endif; ?>
    <link rel="stylesheet" href="<?= asset('css/style.css') ?>">
    <link rel="icon" href="../public/images/3.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav class="navbar">
            <div class="nav-logo">
                <a href="<?= constructUrl('home'); ?>">
                    <img src="<?= asset('images/nav-logo.png') ?>" alt="">
                </a>
            </div>
            <div class="nav-links">
                <?php if (!isConnected()) : ?>
                    <a class="nav-link text-light" href="<?= constructUrl('login'); ?>">Connexion/Inscription</a>
                <?php else : ?>
                    <a class="nav-link text-light" href="<?= constructUrl('userModify') ?>">Profil</a>
                    <a class="nav-link text-light" href="<?= constructUrl('panier'); ?>">Panier</a>
                    <a class="nav-link text-light" href="<?= constructUrl('logout'); ?>">Se déconnecter</a>
                <?php endif; ?>
            </div>
        </nav>
    </header>

    <main>
        <!-- Message flash -->
        <?php if (isset($flashMessage) && $flashMessage) : ?>
            <p class="alert alert-success text-center"><?= $flashMessage ?></p>
        <?php endif; ?>

        <!-- Contenu de la page -->
        <?php include $template . '.phtml'; ?>
    </main>
</body>

</html>