<div class="logo-login">
    <img src="<?= asset('images/logo-form.png') ?>" alt="">
</div>

<form action="" method="POST">
    <input type="text" name="email" placeholder="Email">
    <input type="password" name="password" placeholder="Mot de passe">
    <?php if (isset($errors['email'])) : ?>
        <p class="alert alert-danger"><?= $errors['email']; ?></p>
    <?php endif; ?>
    <button class="button" type="submit">Se connecter</button>
</form>
<p class="register-btn">Vous n'êtes pas inscrit ? <a class="click" href="<?= constructUrl('register'); ?>">cliquez ici</a></p>