<img src="<?= asset('images/logo-form.png') ?>" alt="">

<form action="" method="POST">
    <input type="text" name="email" placeholder="Email">
    <input type="password" name="password" placeholder="Mot de passe">
    <?php if (isset($errors['email'])) : ?>
        <p class="alert alert-danger"><?= $errors['email']; ?></p>
    <?php endif; ?>
    <button type="submit">Se connecter</button>
</form>
<p>Vous n'êtes pas inscrit ? <a href="<?= constructUrl('register'); ?>">cliquez ici</a></p>