<div class="logo-home">
    <img class="" src="<?= asset('images/big-logo.png') ?>" alt="">
</div>

<div class="all-cards">
    <?php foreach ($foods as $food) : ?>
        <div class="card">
            <img class="img-food" src="<?= asset('images/' . $food->getImage()) ?>" alt="">
            <div>
                <h1 class="title-food"><?= $food->getTitle(); ?></h1>
                <p class="content-food"><?= $food->getDescription() ?></p>
                <div class="add-price">
                    <h1 class="price-food"><?= $food->getPrice() ?> €</h1>
                    <button class="button">Ajouter au panier</button>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<footer></footer>