<header>
    <nav class="navbar">
        <div class="nav-content">
            <div class="nav-logo">
                <a href="<?= constructUrl('/'); ?>">
                    <img src="<?= asset('images/nav-logo.png') ?>" alt="">
                </a>
            </div>
            <div class="nav-links">
                <a href="">Profil</a>
                <a href="<?= constructUrl('/panier'); ?>">Panier</a>
                <a href="<?= constructUrl('/connexion'); ?>">Connexion/Inscription</a>
                <a href="">Se déconnecter</a>
            </div>
        </div>

    </nav>
</header>


<img src="<?= asset('images/logo-form.png') ?>" alt="">

<form action="">
    <input type="text" name="firstname" placeholder="Nom">
    <input type="text" name="lastname" placeholder="Prénom">
    <input type="mail" name="mail" placeholder="Email">
    <input type="tel" name="phone" placeholder="Téléphone">
    <input type="password" name="password" placeholder="Mot de passe">
    <button type="submit">S'inscrire</button>
</form>