<h1 class="title">Admin</h1>
<form action="" method="POST">
    <input type="text" name="email" placeholder="Email">
    <input type="password" name="password" placeholder="Mot de passe">
    <?php if (isset($errors['email'])) : ?>
        <p class="alert alert-danger"><?= $errors['email']; ?></p>
    <?php endif; ?>
    <?php if (isset($errors['role'])) : ?>
        <p class="alert alert-danger"><?= $errors['role']; ?></p>
    <?php endif; ?>
    <button class="button" type="submit">Se connecter</button>
</form>