<form action="" method="POST">
    <label for="firstname">Nom</label>
    <input type="text" name="firstname" id="firstname" value="<?= $firstname ?>">

    <label for="lastname">Prénom</label>
    <input type="text" name="lastname" id="lastname" value="<?= $lastname ?>">

    <label for="email">Email</label>
    <input name="email" id="email" value="<?= $email ?>">

    <label for="phone">Téléphone</label>
    <input type="text" name="phone" id="phone" value="<?= $phone ?>">

    <label for="address">Adresse</label>
    <textarea name="address" id="address"><?= $address ?></textarea>

    <button class="button" type="submit">Enregistrer</button>
</form>